server:
  port: 9000

spring:
  application:
    name: telegram

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public
      connection-timeout: 5000

  liquibase:
    default-schema: public

  jpa:
    open-in-view: false